name: Deploy to S3

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: angular-build
          path: dist/simulacert/browser

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 sync \
            dist/simulacert/browser \
            s3://simulacert-app-prod \
            --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1F2G7KCZXOOIL \
            --paths "/*"
